### PR TITLE
Fix grammar in readme.md

### PR DESCRIPTION
**Pull request by nishu88**
Addresses issue #89

### CODE REVIEW

**Review by pontakornth — CHANGES_REQUESTED** [review]
All changes are just whitespace. There is no grammatical change.

**Comment by nishu88** [comment]
Hi, sorry for that, the markdown editor i used added extra whitespaces.. I removed them :) @pontakornth

**Comment by HelloYeew** [comment]
About the change I will accept it but I have to talk with other in the team about merging. But, thanks for contribution!

**Comment by LumpBloom7** [comment]
Closing in favor of #94.

**Pull request closed without merging**
